### ISSUE TITLE
主题皮肤按键

### ISSUE THREAD

**Issue by Chengxcy** [chwt163/mytrime#1]
现在用的是小企鹅装的rime插件，没有用同文主要是同文的主题皮肤太难配置了，没有找到适合自己用的主题。在trime那里看到你设计的主题皮肤挺好看的，个人感觉有点简约了，还有主题皮肤的字母按键用大写的是不是好看一点？![Screenshot_20240502_032345_GitHub.jpg](https://github.com/chwt163/mytrime/assets/91258009/f857471d-58ba-43bf-8411-3722adf52a5f)

**Comment by chwt163** [comment]
可以实现，在键盘布局里：
label_transform: 中文模式下按键字母标签自动大写（uppercase：自动大写，仅对单个字母生效，长标签请直接更改lable；none：无，可省略不写）

详见：
[trime.yaml詳解](https://github.com/mrhso/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80)

**Comment by linzianxyz** [comment]
然后没有直接的中英切换吧？

**Comment by chwt163** [comment]
> 然后没有直接的中英切换吧？

通常输入方案自带的工具栏按钮，已经有中英切换的功能了吧？
你也可以自己添加到键盘里面去。
