### ISSUE TITLE
如何修改为36键布局？

### ISSUE THREAD

**Issue by theLSA** [chwt163/mytrime#3]
这个主题还不错，但是我想要36键的布局（数字键在最上面一行），尝试了以下操作都无效（还是主题的26键布局）
1. big.trime.yaml 中设定：

```
preset_keyboards:  
  rime_ice:
    __include: /preset_keyboards/qwerty0
```

2. rime目录新增trime.custom.yaml写入：

```
patch:  
  "preset_keyboards/rime_ice/import_preset": qwerty0   #预设36键布局的ID是qwerty0  
```

请问要如何设置让这个主题的数字键在最上面一行？

**Comment by chwt163** [comment]
直接把第一行键盘“qwertyuiop”复制粘贴一遍，就会增加一行键盘，再把“qwertyuiop”改成数字。
还要调整一下键盘高度：
> keyboard_height: 220 #锁定键盘高度，避免切换时键盘高度变化而造成闪烁

![Screenshot_20240815_232600_net gsantner markor](https://github.com/user-attachments/assets/217ef1b9-2625-4276-be7c-7e2663463213)
![Screenshot_20240815_232755_net gsantner markor](https://github.com/user-attachments/assets/1edb8c70-128f-49fb-a4e7-49b9fd6ef1ae)

**Comment by theLSA** [comment]
非常感谢！已成功修改！
