### ISSUE TITLE
如何在菜单新增开关？

### ISSUE THREAD

**Issue by theLSA** [chwt163/mytrime#5]
想要在开关表情旁边加上开关符号，符号是自定义的

trime版本：
[3.2.16](https://github.com/osfans/trime/releases/download/v3.2.16/trime-3.2.16-arm64-v8a-debug.apk)

主题：
https://github.com/chwt163/mytrime/blob/main/v3.2.18/big.trime.yaml

配置：
https://github.com/iDvel/rime-ice

操作步骤如下：
1. 将 [rime-symbols](https://github.com/fkxxyz/rime-symbols) 生成的三个符号文件(json及txt)放到opencc目录下

2. rime_ice.custom.yaml添加一个symbol_support开关
```
......
      name: emoji
      states: [ ∷, ☻ ]
      reset: 0
      name: symbol_support
      states: [ "c", "o" ]
      reset: 1
......
```

3. rime_ice.custom.yaml添加
```
  'engine/filters/@before 0':
    simplifier@symbol_support
  symbol_support:
    opencc_config: symbol.json
    option_name: symbol_support
    tips: all
```

但是这样部署后，开关表情按键没了，而且配置是默认关表情却开启了，符号也没开启，请问需要如何配置？
（上述配置在debian的ibus-rime下有效）

**Comment by theLSA** [comment]
name前要有 - ，已解决。

**Comment by K7ISY4** [comment]
3.3.0不生效
